### ISSUE TITLE
LatLon Assumption

### ISSUE THREAD

**Issue by brycefrank** [highamm/sptotal#4]
In other statistical packages I have used (i.e. `geoR`) it is left to the user to define and handle the coordinate system. I see here we make the assumption that they are already Lat/Lon:

https://github.com/highamm/sptotal/blob/e0f7f50bde34a9a87f7ec253531039216fab57bc/R/slmfit.R#L84-L95

This has been a point of discussion in meetings. I would rather not assume anything about the data structure, and leave it to the user to reproject. Or, if we are wedded the the reprojecting idea, we need to at least print a warning when `slmfit` runs.

**Comment by highamm** [comment]
Noted and changed so that we now assume that the user has already reprojected any coordinates into a reasonable projection.
