### ISSUE TITLE
Error on `slmfit` without factor

### ISSUE THREAD

**Issue by brycefrank** [highamm/sptotal#5]
I am writing some tests on my own branch, so not sure if this is just me. The following fit using the simdata throws an error:

```
fit <- sptotal::slmfit(Z ~ X1 + X2 + X3 + X4+ X5 + X6 + X7, data=simdata, xcoordcol = "x", ycoordcol="y")
```

The error:

```
Error in max(sapply(datapredsonly[, sapply(datapredsonly, is.factor)],  : 
  invalid 'type' (list) of argument
```

Fitting again, but with a factor variable resolves the issue:

```
fit <- sptotal::slmfit(Z ~ X1 + X2 + X3 + X4+ X5 + X6 + X7 + F1, data=simdata, xcoordcol = "x", ycoordcol="y")
```

**Comment by brycefrank** [comment]
Confirmed to be a bug on the current master branch. It seems to be a problem with this line:

https://github.com/highamm/sptotal/blob/9cd64ce4167d0f652a8de1eb3d026964bfcaf7ac/R/slmfit.R#L112-L114

**Comment by highamm** [comment]
Fixed issue by adding a line to check if any of the variables are factors before checking to make sure that the number of factor levels is reasonable. Thank you!
