### ISSUE TITLE
code quality & test coverage

### ISSUE THREAD

**Issue by fabian-s** [highamm/sptotal#7]
code quality checks by `goodpractice::gp(".")`  return the following issues:

```
Preparing: covr
Preparing: cyclocomp
Preparing: description
Preparing: lintr
Preparing: namespace
Preparing: rcmdcheck
── GP sptotal ──────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code in
    general. 43% of code lines are covered by test cases.

    R/AIC.slmfit.R:17:NA
    R/AIC.slmfit.R:18:NA
    R/coef.slmfit.R:14:NA
    R/coef.slmfit.R:15:NA
    R/coef.slmfit.R:16:NA
    ... and 503 more lines

  ✖ omit "Date" in DESCRIPTION. It is not required and it gets
    invalid quite often. A build date will be added to the package when
    you perform `R CMD build` on it.
  ✖ use '<-' for assignment instead of '='. '<-' is the
    standard, and R users and developers are used it and it is easier
    to read your code for them if you use '<-'.

    inst/scripts/create_simulated_data.r:4:4
    inst/scripts/create_simulated_data.r:12:5
    inst/scripts/create_simulated_data.r:18:4
    inst/scripts/create_simulated_data.r:20:4
    inst/scripts/create_simulated_data.r:22:4
    ... and 22 more lines

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    R/AIC.slmfit.R:5:81
    R/AIC.slmfit.R:6:81
    R/data.R:27:81
    R/data.R:32:81
    R/data.R:39:81
    ... and 114 more lines

  ✖ avoid sapply(), it is not type safe. It might return a
    vector, or a list, depending on the input data. Consider using
    vapply() instead.

    R/slmfit.R:214:15
    R/slmfit.R:216:17
    R/slmfit.R:216:40

  ✖ avoid 1:length(...), 1:nrow(...), 1:ncol(...), 1:NROW(...)
    and 1:NCOL(...) expressions. They are error prone and result 1:0 if
    the expression on the right hand side is zero. Use seq_len() or
    seq_along() instead.

    inst/scripts/create_simulated_data.r:38:58
    inst/scripts/create_simulated_data.r:41:58
    R/utils.R:101:15
    vignettes/sptotal-vignette.Rmd:178:17
    vignettes/sptotal-vignette.Rmd:471:21

  ✖ not import packages as a whole, as this can cause name
    clashes between the imported packages. Instead, import only the
    specific functions you need.
```

increasing test coverage, replacing 1:<Variable> iterators, and cleaning up/reducing the imports (if possible) seem important to me, the rest is mroe or less cosmetic...

**Comment by fabian-s** [comment]
see also [joss-reviews/#5283](https://github.com/openjournals/joss-reviews/issues/5283)

**Comment by fabian-s** [comment]
see also https://github.com/openjournals/joss-reviews/issues/5363

**Comment by highamm** [comment]
Hello! Thanks again for getting this started. I just have a quick update that we've added a bit more testing with the newer major release of testthat. We have also changed the 1:n_iter and sapply() code in the latest push. There are still some tests we plan on adding this week to address some of the lines of code still not covered, but we have made some progress. Below is the output from `goodpractice::gp(".")` on the newest version.

```
── GP sptotal ────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code
    in general. 89% of code lines are covered by test cases.

    R/plot.slmfit.R:33:NA
    R/predict.slmfit.R:53:NA
    R/predict.slmfit.R:54:NA
    R/predict.slmfit.R:71:NA
    R/predict.slmfit.R:72:NA
    ... and 94 more lines

  ✖ avoid long code lines, it is bad for readability. Also,
    many people prefer editor windows that are about 80 characters
    wide. Try make your lines shorter than 80 characters

    R/data.R:109:81
    R/data.R:111:81
    R/data.R:112:81
    R/data.R:113:81

  ✖ not import packages as a whole, as this can cause name
    clashes between the imported packages. Instead, import only the
    specific functions you need. 
```

**Comment by fabian-s** [comment]
great, thx! 

89% coverage seems fine to me already, long code lines are irrelevant.

just checked your imports: if you adapt https://github.com/highamm/sptotal/blob/7b5ecd9ae733ae62c6d6bb0a8eba13fe32418c20/R/print.summary.slmfit.R#L23, https://github.com/highamm/sptotal/blob/7b5ecd9ae733ae62c6d6bb0a8eba13fe32418c20/R/print.summary.slmfit.R#L74 to use @importFrom and pick the specific stats-functions you need this is perfect as well.

EDIT:
importing all of ggplot2 and graphics seems fine to me.
there are some more lines where you import all of stats in other roxygen-blocks, see https://github.com/highamm/sptotal/search?q=import

**Comment by highamm** [comment]
Sounds good! The most recent commit [3c914c3](https://github.com/highamm/sptotal/commit/3c914c3d763b9b0882d67655a3d7a9f24c870864) fixed these import issues (and addresses the `ggplot2` and `graphics` imports: looking at them again helped me catch the fact that we no longer need to import anything from `viridis`, whose main functions now come bundled with `ggplot2`).

Thank you again for the suggestion!
