### ISSUE TITLE
Paper comments

### ISSUE THREAD

**Issue by garretrc** [highamm/sptotal#8]
Paper looks great! Some feedback from my review (all from the statement of need section):

What assumptions are made on the distribution of epsilon? I would assume it's normal, but might not be clear for someone new to spatial stats. 

Additionally, you denote that y has N locations but don't use N anywhere else. You could use N to clarify some of the model terms, for example,  R is N x N, providing spatial correlation from each of the N locations to all others. (similar to the above point, it may help someone who is familiar to linear models but not spatial stats)

Otherwise, everything reads clear to me and I learned quite a bit about what the package does. It's clear the advantages this method has over other available approaches.

**Comment by highamm** [comment]
Hi @garretrc,

Thank you for these helpful comments! I've just pushed a new version that has some edits based on your comments, including 

* a clarification that the distribution of the random errors is assumed normal (this is not a strict assumption for the method itself, which is moment-based, but the REML estimation of the model parameters in the package does assume normality),
* a little bit more text describing R and some clarification for the reader that y and b are both N-length vectors and that R is N x N.

I'll leave the issue open for now in case you have any other comments about the paper as you continue the review. Thanks again!
